### ISSUE TITLE
The website does not work properly on google chrome

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [timjb/svd-image-compression-demo#23]
The demo application on the `http://timbaumann.info/svd-image-compression-demo/` does not work on google chrome `Version 92.0.4515.107 (Official Build) (64-bit)`. The status remains on the `please wait` text.

The raised exception on the console:
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': ArrayBuffer is not detachable and could not be cloned.
    at http://timbaumann.info/svd-image-compression-demo/svd-worker.worker.js:1:651
```
The app workss fine on firefox.

```
OS: Manjaro Linux
```

**Comment by timjb** [comment]
@alirezaafzalaghaei Should be fixed now. Thanks for bringing this to my attention!
