### ISSUE TITLE
Hi Tim,  npm install fails to install image-svd. I tried installing it manually but it is not available. Can you please share the link for image-svd module?

### ISSUE THREAD

**Issue by rakheshkumbi** [timjb/svd-image-compression-demo#5]

**Comment by timjb** [comment]
The `image-svd` module is defined in `/src/main-app/image-svd.ts`.

I have now added a `package-lock.json` file that records the specific versions of dependencies. This should hopefully help with making builds more reproducible. Can you please try again (follow the instructions in the README) and let me know if it works now?
